package coursework;

import java.util.Random;
import javax.swing.JOptionPane;

public class Hangman extends javax.swing.JFrame {

    public char[] currentword;
    public int tnumber;
    /**
     * Creates new form NewJFrame
     */
    public Hangman() {
        initComponents();
        Random ran = new Random();
        int num = ran.nextInt(7 - 1) + 1;
        currentword = wordlist(num);
        int arrlength = currentword.length;
        exes(arrlength);

    }

    public final char[] wordlist(int num) {
        char[] v = {'h', 'e', 'l', 'l', 'o'};
        char[] w = {'t', 'r', 'a', 'm', 'p', 'o', 'l', 'i', 'n', 'e'};
        char[] z = {'d', 'e', 's', 'i', 'g', 'n'};
        char[] x = {'h', 'i', 's', 't', 'o', 'r', 'y'};
        char[] c = {'f', 'o', 'r', 'm'};
        char[] b = {'c', 'e', 'n', 't','i', 'p', 'e', 'd', 'e'};
        char[] y = {};
        char[] arr = null;
        switch (num) {
            case 1:
                arr = v;
                break;
            case 2:
                arr = w;
                break;
            case 3:
                arr = z;
                break;
            case 4:
                arr = x;
                break;
            case 5:
                arr = c;
            case 6:
                arr = b;
                
        }
        return arr;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entryfield = new javax.swing.JTextField();
        btntry = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Enterybt = new javax.swing.JLabel();
        exitbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entryfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryfieldActionPerformed(evt);
            }
        });

        btntry.setText("Try Letter");
        btntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntryActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/h0.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(entryfield, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntry)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Enterybt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Enterybt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(entryfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btntry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntryActionPerformed
       
        char[] v = currentword;
        char n;
        StringBuilder guess = new StringBuilder(Enterybt.getText()); 
       
        n = entryfield.getText().charAt(0);
        n = Character.toLowerCase(n);
        boolean flag = false;
        int index = 0;
        int indexc = 0;
        boolean flag2 = false;
        while (index < (v.length)) {
            if (n == (v[index])) {
                flag = true;
                indexc = index;
                guess.setCharAt(2*index, n);
                String stringguess = guess.toString();
                Enterybt.setText(stringguess);
            } else {
                flag = false;
                
            }
            index++;
            if (flag == true) {
                flag2 = true;
            }

        }

        if (flag2 == true) {
            JOptionPane.showMessageDialog(null, "Correct", "Hangman", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null, "Wrong", "Hangman", JOptionPane.INFORMATION_MESSAGE);
            tnumber++;
        }

    }//GEN-LAST:event_btntryActionPerformed


    private void entryfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryfieldActionPerformed

    }//GEN-LAST:event_entryfieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, ""+(6-tnumber)+" tries remaining", "Tries Remaining", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new Hangman().setVisible(true);
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Enterybt;
    private javax.swing.JButton btntry;
    private javax.swing.JTextField entryfield;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void exes(int length) {
        switch (length) {
            case 3:
                Enterybt.setText("X X X");
                break;
            case 4:
                Enterybt.setText("X X X X");
                break;
            case 5:
                Enterybt.setText("X X X X X");
                break;
            case 6:
                Enterybt.setText("X X X X X X");
                break;
            case 7:
                Enterybt.setText("X X X X X X X");
                break;
            case 8:
                Enterybt.setText("X X X X X X X X");
                break;
            case 9:
                Enterybt.setText("X X X X X X X X X");
                break;
            case 10:
                Enterybt.setText("X X X X X X X X X X");
                break;
        }
    }
}
