package coursework;

import java.util.*;
import javax.swing.JOptionPane;

public class Hangman extends javax.swing.JFrame {

    public char[] currentWord;
    public int numberOfTries;
    public int numberCorrect;

    /**
     * Creates new form NewJFrame
     */
    public Hangman() {
        initComponents();
        Random ran = new Random();
        int num = ran.nextInt(7 - 1) + 1;
        currentWord = {'h','e','l','l','o'};
        

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entryField = new javax.swing.JTextField();
        btnTry = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        wordHolder = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        hangStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryFieldActionPerformed(evt);
            }
        });

        btnTry.setText("Try Letter");
        btnTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        hangStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/h0.png"))); // NOI18N
        hangStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hangStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(entryField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTry)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wordHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hangStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(wordHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(entryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnTry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hangStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryActionPerformed

        body();
        
    }
    
    private void body(){
         char[] wordArray = currentWord;
        char wordGuess;
        StringBuilder guess = new StringBuilder(wordHolder.getText());

        wordGuess = entryField.getText().charAt(0);
        wordGuess = Character.toLowerCase(wordGuess);

        boolean flag = false;
        int index = 0;
        int indexc = 0;
        boolean flag2 = false;
        while (index < (wordArray.length)) {
            if (wordGuess == (wordArray[index])) {
                flag = true;
                indexc = index;
               
                String stringguess = guess.toString();
                wordHolder.setText(stringguess);

            } else {
                flag = false;

            }
            index++;
            if (flag == true) {
                flag2 = true;
            }

        }

        if (flag2 == true) {
            JOptionPane.showMessageDialog(null, "Correct", "Hangman", JOptionPane.INFORMATION_MESSAGE);
            numberCorrect++;
               
           
        } else {
            JOptionPane.showMessageDialog(null, "Wrong", "Hangman", JOptionPane.INFORMATION_MESSAGE);
            numberOfTries++;
            if (numberOfTries == 1) {
                hangStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/h1.png")));
            } else if (numberOfTries == 2) {
                hangStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/h2.png")));
            } else if (numberOfTries == 3) {
                hangStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/h3.png")));
            } else if (numberOfTries == 4) {
                hangStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/h4.png")));
            } else if (numberOfTries == 5) {
                hangStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/h5.png")));
            } else if (numberOfTries == 6) {
                hangStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/h6.png")));
                System.exit(0);
            }
        }
    }

    private void entryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryFieldActionPerformed

    }//GEN-LAST:event_entryFieldActionPerformed

    private void hangStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hangStatusActionPerformed
        
    }//GEN-LAST:event_hangStatusActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new Hangman().setVisible(true);
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTry;
    private javax.swing.JTextField entryField;
    private javax.swing.JButton hangStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel wordHolder;
    // End of variables declaration//GEN-END:variables

   
}
